blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #apps
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('posts.urls')),
    path('', include('categoria.urls')),
    path('',include('comentarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categoria/urls.py
from django.urls import path
from categoria.views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView

app_name = 'categoria'

urlpatterns = [
    path('categoria', CategoriaListView.as_view(),name='categorias_categoria'),
    path('adicionarcategoria', CategoriaCreateView.as_view(), name='adicionar_categoria'),
    path('categoria/<int:pk>/editar',CategoriaUpdateView.as_view(), name='updatecat_post'),
    path('categoria/<int:pk>/deletar',CategoriaDeleteView.as_view(), name='deletecat_categoria'),
]

posts/urls.py
from django.urls import path
from posts.views import PostListView, PostCreateView, PostUpdateView, PostDeleteView, PostDetailView

app_name = 'posts'

urlpatterns = [
    path('post', PostListView.as_view(),name='pagina_post'),
    path('adicionar', PostCreateView.as_view(), name='criar_post'),
    path('posts/<int:pk>/editar',PostUpdateView.as_view(), name='update_post'),
    path('posts/<int:pk>/deletar',PostDeleteView.as_view(), name='delete_post'),
    path('posts/<int:pk>/detalhes', PostDetailView.as_view(),name='detail_post'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#lembrando que qualquer alteração aqui, deve ser feito makemigrations
class Post(models.Model):
    autor = models.ForeignKey("users.User", verbose_name='autor', 
    related_name='postsFromUser', on_delete=models.CASCADE) 
    categoria = models.ForeignKey("categoria.Categoria", verbose_name='categoria', on_delete=models.CASCADE)
    post = models.TextField(verbose_name='texto') 
    created_at = models.DateTimeField( auto_now=True, verbose_name='criado em')
    image = models.ImageField(blank=True,verbose_name='imagem', upload_to='posts')
    def __str__(self):
        return f'post {self.pk} | Publicado por {self.autor} | em {self.created_at}'

posts/forms.py
from django import forms
from posts.models import Post

class PostCreateForm(forms.ModelForm):
    class  Meta: #quando quer mudar a propriedade de alguém que foi herdado do que já exite no django
        model = Post
        fields = ['autor', 'categoria', 'post','image'] #outro aqui pra categoria
    

posts/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView,CreateView, UpdateView, DeleteView, DetailView
from posts.models import Post
from posts.forms import PostCreateForm
from django.urls import reverse_lazy 
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'posts/post.html'
    ordering = ['-created_at']

class PostCreateView(LoginRequiredMixin, CreateView): 
    model = Post
    form_class = PostCreateForm
    template_name = 'posts/createpost.html'
    success_url = reverse_lazy('posts:pagina_post')  #ordem de postagem

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['autor', 'post','categoria']
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:pagina_post')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    context_object_name = 'post' 
    template_name = 'posts/delete.html' #leva para o html do template
    success_url = reverse_lazy('posts:pagina_post')

class PostDetailView(DetailView):
    model = Post 
    context_object_name = 'posts'
    template_name = 'posts/detailpost.html'   

templates/posts/createpost.html
{% extends 'base.html' %}
{% load static  %}
{% load widget_tweaks %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block head %}
{% block style %} 




{% endblock style %}
{% endblock head %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <p>Autor: {% render_field form.autor %} </p>
   <p>Categoria: {% render_field form.categoria %}</p>
   <p> {% render_field form.post %}</p>

   <p>{% render_field form.image %}</p>
   
    <input type ="submit" value="Enviar">
</form>
  

{% endblock body %}

templates/posts/delete.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block style %} 




{% endblock style %}
{% block body %}

<form method="post">
        {% csrf_token %}
        <p>Você tem certeza que quer excluir o post abaixo?</p>
        {{post.texto}}
<input type="submit" value="Deletar">
    </form>
</form>

{% endblock body %}

templates/posts/detailpost.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Comentarios
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}

{% block style %} 


{% endblock style %}

{% block body %}
<h5>Detalhes</h5>
<p> Autor:    {{posts.autor}} </p>

<p>Categoria:    {{posts.categoria}} </p>
<p> Postagem:     {{posts.post}}    </p>

{% for p in posts.commentsFromPost.all %}

    <p> Comentarios: {{p.comentario}}</p>
    {% empty %}
    <p>Esse post não tem comentarios ):</p>
{% endfor %}      
    </div>

{% endblock body %}

templates/posts/post.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}

{% block style %} 


{% endblock style %}

{% block body %}
<div class="AllDivs">
{% for p in posts %}
    <div class =  "Divisao">
    {%if p.image %}
    
    <p><img src = "{{p.image.url}}"></p>
{% endif %}
    <center><p> {{p.post}} </p><br></center>

    <center><p> {{p.autor}} </p>
    <a href="{% url 'categoria:updatecat_post' p.categoria.id %}">{{p.categoria}}</a>/
    <a href="{% url 'categoria:deletecat_categoria' p.categoria.id %}">Deletar</a>
    </center>
    <p> {{p.created_at}} </p><br>
    <center>
    <a href="{% url 'posts:update_post' p.id %}">editar</a> 
    <a href="{% url 'posts:delete_post' p.id%}">deletar</a></center>
    <a href="{% url 'posts:detail_post' p.id %}">detalhes</a>
    </div>
{% endfor %}    
</div>
{% endblock body %}

templates/posts/update.html
{% extends 'base.html' %}

{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block style %} 




{% endblock style %}
{% block body %}
<div class = "BgUpdatePost">
    <h3>Editar Postagem</h3>

    <form method="post">    
    {% csrf_token  %}
    {{form.as_p}}
    <input type="submit" value="Editar">

    </form>
</div>
{% endblock body %}