blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #apps
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('posts.urls')),
    path('', include('categoria.urls')),
    path('',include('comentarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categoria/urls.py
from django.urls import path
from categoria.views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView

app_name = 'categoria'

urlpatterns = [
    path('categoria', CategoriaListView.as_view(),name='categorias_categoria'),
    path('adicionarcategoria', CategoriaCreateView.as_view(), name='adicionar_categoria'),
    path('categoria/<int:pk>/editar',CategoriaUpdateView.as_view(), name='updatecat_post'),
    path('categoria/<int:pk>/deletar',CategoriaDeleteView.as_view(), name='deletecat_categoria'),
]

core/urls.py
from django.urls import path
from core.views import index

app_name = 'core'

urlpatterns = [
      path('',index,name='index'), #pagina inicial, view, name
]

posts/urls.py
from django.urls import path
from posts.views import PostListView, PostCreateView, PostUpdateView, PostDeleteView, PostDetailView

app_name = 'posts'

urlpatterns = [
    path('post', PostListView.as_view(),name='pagina_post'),
    path('adicionar', PostCreateView.as_view(), name='criar_post'),
    path('posts/<int:pk>/editar',PostUpdateView.as_view(), name='update_post'),
    path('posts/<int:pk>/deletar',PostDeleteView.as_view(), name='delete_post'),
    path('posts/<int:pk>/detalhes', PostDetailView.as_view(),name='detail_post'),
]

users/urls.py
from django.urls import path
from users.views import UserListView, UserLoginView, UserLogoutView, UserSignUpView, UserDetailView 


app_name = 'users'

urlpatterns = [
    path('list',UserListView.as_view(),name='list_users'), 
    path('login', UserLoginView.as_view(),name='login_users'),   
    path('logout', UserLogoutView.as_view(),name='logout_users'),
    path('signup', UserSignUpView.as_view(),name='signup_users'),
    path('users/<int:pk>/detalhes', UserDetailView.as_view(),name='detail_users'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{%endblock title %}</title>
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="node_modules/bootstrap/compiler/stylenavs.css">
    
    {% block style %} {% endblock style %}

</head>
<body>

        <nav class="navbar navbar-dark bg-dark">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="{% url 'core:index' %}">Hello</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Alterna navegação">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                          <ul class="navbar-nav">
                            <li class="nav-item active">
                              <a class="nav-link" href="{% url 'posts:pagina_post' %}">Postagens <span class="sr-only">(Página atual)</span></a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'comentarios:comentario_comentarios' %}">Comentários</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'users:list_users' %}">Usuários</a>
                            </li>
                            
                          {% if not request.user.is_authenticated %}  
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'users:login_users' %}">Login</a>
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'users:signup_users' %}">  SignUp  </a>
                          </li>      
                          </li>  
                          {% else %}
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:detail_users' request.user.id %}">  {{request.user}}  </a>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'users:logout_users' %}">  Logout  </a>
                            </li>   
                          </li>
                          {% endif %}
                            
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="{% url 'posts:criar_post' %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Criar 
                              </a>
                              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'posts:criar_post' %}">Postar</a>
                                <a class="dropdown-item" href="{% url 'comentarios:criarcoment_comentarios' %}">Comentar</a>
                                <a class="dropdown-item" href="{% url 'categoria:adicionar_categoria' %}">Criar Categoria</a>
                               
                              </div>
                            </li>
                          </ul>
                        </div>
                      </nav>
      </nav>
    {% block body %}
    {% endblock body %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>