blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #apps
    path('', include('core.urls')),
    path('',include('users.urls')),
    path('', include('posts.urls')),
    path('', include('categoria.urls')),
    path('',include('comentarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comentarios/urls.py
from django.urls import path
from comentarios.views import ComentariosListView,ComentariosCreateView, ComentariosUpdateView, ComentariosDeleteView

app_name = 'comentarios'

urlpatterns = [
    path('comentarios', ComentariosListView.as_view(),name='comentario_comentarios'),
    path('criarcomentario', ComentariosCreateView.as_view(),name='criarcoment_comentarios'),
    path('comentarios/<int:pk>/editar',ComentariosUpdateView.as_view(), name='updatecoment_comentarios'),
    path('comentarios/<int:pk>/deletar',ComentariosDeleteView.as_view(), name='deletecoment_comentarios'),
    
]

comentarios/models.py
from django.db import models

# Create your models here.
class Comentarios(models.Model):
    post = models.ForeignKey("posts.Post", verbose_name='post', 
    related_name='commentsFromPost', on_delete=models.CASCADE)
    comentario = models.TextField(verbose_name='comentario')
    created_at = models.DateTimeField( auto_now=True)
    
    class Meta:
        verbose_name='Comentario'
        verbose_name_plural = 'Comentarios'

comentarios/forms.py
from django import forms
from comentarios.models import Comentarios

class ComentariosCreateForm(forms.ModelForm):
    class  Meta: #quando quer mudar a propriedade de alguém que foi herdado do que já exite no django
        model = Comentarios
        fields = ['post','comentario',] #outro aqui pra categoria
    

comentarios/views.py
from django.shortcuts import render
from comentarios.models import Comentarios
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy 
from comentarios.forms import ComentariosCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class ComentariosListView(ListView):
    model = Comentarios
    context_object_name = 'comentarios' #o que vai ser chamado no for do html
    template_name = 'comentario/listcomentario.html'
    ordering = ['-created_at']

class ComentariosCreateView(LoginRequiredMixin, CreateView): 
    model = Comentarios
    form_class = ComentariosCreateForm
    template_name = 'comentario/createcomentario.html'
    success_url = reverse_lazy('comentarios:comentario_comentarios')    

class ComentariosUpdateView(LoginRequiredMixin, UpdateView):
    model = Comentarios
    fields = ['comentario']
    template_name = 'comentario/updatecoment.html'
    success_url = reverse_lazy('comentarios:comentario_comentarios')  
    
class ComentariosDeleteView(LoginRequiredMixin, DeleteView):
    model = Comentarios
    context_object_name = 'comentarios' 
    template_name = 'comentario/deletecoment.html' #leva para o html do template
    success_url = reverse_lazy('comentarios:comentario_comentarios')

templates/comentario/createcomentario.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}

{% block style %} 




{% endblock style %}
{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type ="submit" value="Enviar">
</form>
  

{% endblock body %}

templates/comentario/deletecoment.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block style %} 




{% endblock style %}
{% block body %}

<form method="post">
        {% csrf_token %}
        <p>Você tem certeza que quer excluir o comentario abaixo?</p>
        {{post.texto}}
<input type="submit" value="Deletar">
    </form>
</form>

{% endblock body %}

templates/comentario/listcomentario.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Usuarios
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block style %} 

{% endblock style %}
{% block body %}

{% for c in comentarios %}
    <div class= "Enquadramento">
    <p> {{c.post}} </p><br>
    <p> {{c.comentario}} </p>
    <a href="{% url 'comentarios:updatecoment_comentarios' c.id %}">editar</a>/ 
    <a href="{% url 'comentarios:deletecoment_comentarios' c.id%}">deletar</a>
</div>
{% endfor %}    

{% endblock body %}

templates/comentario/updatecoment.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
     Blog|Postagens
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock scripts %}
{% block style %} 


{% endblock style %}s
{% block body %}

<h3>Editar Postagem</h3>

<form method="post">
{% csrf_token  %}
{{form.as_p}}
<input type="submit" value="Editar">

</form>

{% endblock body %}